thornsNoDurability true
villagerMinimumTradePrice true
soulSpeedNoDurability true
villagerDoNotCraftBread true
commandPlayer true
anvilNoPriorWorkPenalty true
fakePlayerNamePresets [bot_]
villagerUpgradeWhileTrading true
experienceLevelCost 29-30
stackableShulkerBoxes true
